/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Ftc
{
    public class DcMotorOutput : Message
    {
        public const string RosMessageName = "ftc_msgs/DcMotorOutput";

        public float encoder_data { get; set; }

        public DcMotorOutput()
        {
            this.encoder_data = 0.0f;
        }

        public DcMotorOutput(float encoder_data)
        {
            this.encoder_data = encoder_data;
        }
    }
}
