/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Ftc
{
    public class DcMotorInput : Message
    {
        public const string RosMessageName = "ftc_msgs/DcMotorInput";

        public float cmd { get; set; }
        public string mode { get; set; }

        public DcMotorInput()
        {
            this.cmd = 0.0f;
            this.mode = "";
        }

        public DcMotorInput(float cmd, string mode)
        {
            this.cmd = cmd;
            this.mode = mode;
        }
    }
}
